package update

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The ccq-gen2 fixture is the gen-2 output of the ccq gen-1 fixture,
// generated by gen-2 code before the gen-3 template edit. Gen 3's only
// template change (adr.tmpl.md) is embedded-only — absent from update's
// emitted manifest — so updating 2→3 must be exactly the stamp + marker
// diff. Anything else means the gen-3 batch leaked into emitted content.
func TestGen2To3IsStampOnly(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		raw, err := os.ReadFile(filepath.Join("testdata", "ccq-gen2", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	for _, r := range reports {
		switch r.Path {
		case "WORKFLOW.md", "CLAUDE.md":
			if r.State != Pending {
				t.Errorf("%s: want Pending, got %v", r.Path, r.State)
				continue
			}
			for _, line := range strings.Split(r.Diff, "\n") {
				if !strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "-") {
					continue
				}
				if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
					continue
				}
				if strings.Contains(line, "template_version") || strings.Contains(line, "spine:begin") {
					continue
				}
				t.Errorf("%s: unexpected changed line %q — gen 2→3 must be stamp-only", r.Path, line)
			}
		}
	}
}
