package update

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The ccq-gen2 fixture is the gen-2 output of the ccq gen-1 fixture,
// generated by gen-2 code before the gen-3 template edit.
//
// Scope: this lock pins the EMITTED workflow files (WORKFLOW.md, CLAUDE.md)
// from the gen-2 fixture to the CURRENT generation — Run takes no gen pin,
// so after the gen-4 bump it verifies 2→4, after gen 5 it verifies 2→5, and
// so on. That drift is the lock working as intended: any future generation
// that changes emitted content must consciously edit this test. Embedded
// templates (adr/handoff/eval *.tmpl.md) are outside its reach by
// construction — they never appear in update's emitted manifest.
func TestGen2To3IsStampOnly(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		raw, err := os.ReadFile(filepath.Join("testdata", "ccq-gen2", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	seen := map[string]bool{}
	for _, r := range reports {
		switch r.Path {
		case "WORKFLOW.md", "CLAUDE.md":
			seen[r.Path] = true
			if r.State != Pending {
				t.Errorf("%s: want Pending, got %v", r.Path, r.State)
				continue
			}
			for _, line := range strings.Split(r.Diff, "\n") {
				if !strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "-") {
					continue
				}
				if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
					continue
				}
				if strings.Contains(line, "template_version") || strings.Contains(line, "spine:begin") {
					continue
				}
				if isGen5ContentDiffLine(line) { // gen 5's conscious content edit; see gen4to5_test.go
					continue
				}
				if isGen6ContentDiffLine(line) { // gen 6's conscious content edit; see gen5to6_test.go
					continue
				}
				if isGen8ContentDiffLine(line) { // gen 8's conscious content edit; see gen7to8_test.go
					continue
				}
				if isGen9ContentDiffLine(line) { // gen 9's conscious content edit; see gen8to9_test.go
					continue
				}
				t.Errorf("%s: unexpected changed line %q — updates from the gen-2 fixture must be stamp-only", r.Path, line)
			}
		}
	}
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		if !seen[name] {
			t.Errorf("%s: never reported by Run — the stamp-only lock did not exercise it", name)
		}
	}
}
