package update

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The ccq-gen3 fixture is the gen-3 output of the ccq-gen2 fixture,
// generated BY GEN-3 CODE before any gen-4 template edit. Gen 4's template
// changes (handoff.tmpl.md, eval.tmpl.md title quoting) are embedded-only —
// absent from update's emitted manifest — so updating this fixture to the
// CURRENT generation must be exactly the stamp + marker diff. While
// templates/VERSION is still 3 the files report UpToDate (also fine): the
// seen-check accepts any state; the diff scan applies only to Pending.
// Like TestGen2To3IsStampOnly, this lock deliberately drifts forward: a
// future generation changing emitted content must consciously edit it.
func TestGen3To4IsStampOnly(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		raw, err := os.ReadFile(filepath.Join("testdata", "ccq-gen3", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	seen := map[string]bool{}
	for _, r := range reports {
		switch r.Path {
		case "WORKFLOW.md", "CLAUDE.md":
			seen[r.Path] = true
			if r.State != Pending {
				continue // UpToDate pre-bump; Pending stamp-only post-bump
			}
			for _, line := range strings.Split(r.Diff, "\n") {
				if !strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "-") {
					continue
				}
				if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
					continue
				}
				if strings.Contains(line, "template_version") || strings.Contains(line, "spine:begin") {
					continue
				}
				if isGen5ContentDiffLine(line) { // gen 5's conscious content edit; see gen4to5_test.go
					continue
				}
				if isGen6ContentDiffLine(line) { // gen 6's conscious content edit; see gen5to6_test.go
					continue
				}
				if isGen8ContentDiffLine(line) { // gen 8's conscious content edit; see gen7to8_test.go
					continue
				}
				if isGen9ContentDiffLine(line) { // gen 9's conscious content edit; see gen8to9_test.go
					continue
				}
				t.Errorf("%s: unexpected changed line %q — updates from the gen-3 fixture must be stamp-only", r.Path, line)
			}
		}
	}
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		if !seen[name] {
			t.Errorf("%s: never reported by Run — the stamp-only lock did not exercise it", name)
		}
	}
}
