package update

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// gen5ContentLines are the emitted-content changes gen 5 ships: the gates
// line reworded for to-spec + spec-review, and the CLAUDE.md "### Issue
// tracker" block that points wayfinder/to-tickets at the docs/issues ledger.
// Gen 5 is the first content-bearing bump, so the stamp-only locks
// consciously allow exactly these lines and nothing else.
var gen5ContentLines = map[string]bool{
	"Mandatory gates: a PRD up front (grill-with-docs -> to-prd) and verification before completion.":                                                                      true,
	"Mandatory gates: a PRD up front (grill-with-docs -> to-spec), spec-review of the finished diff against the PRD, and verification before completion.":                  true,
	"**Mandatory gates:** a PRD up front (run `/grill-with-docs` -> `/to-prd`) and verification before completion.":                                                        true,
	"**Mandatory gates:** a PRD up front (run `/grill-with-docs` -> `/to-spec`), `/spec-review` of the finished diff against the PRD, and verification before completion.": true,
	"### Issue tracker": true,
	"Issues live as markdown files in `docs/issues/` (the ledger above). `/wayfinder` and `/to-tickets` publish here too — see \"Wayfinding operations\" in `docs/issues/README.md`.": true,
}

// isGen5ContentDiffLine reports whether a unified-diff line carries one of
// the gen-5 content changes (or is a bare added/removed blank line from the
// Issue tracker block's spacing).
func isGen5ContentDiffLine(line string) bool {
	if len(line) == 0 || (line[0] != '+' && line[0] != '-') {
		return false
	}
	body := strings.TrimSpace(line[1:]) // diff rows render as "+ content" / "- content"
	return body == "" || gen5ContentLines[body]
}

// The ccq-gen4 fixture is the gen-4 output of the ccq-gen3 fixture,
// generated BY GEN-4 CODE before any gen-5 template edit. Gen 5 changes
// emitted content, so — unlike the earlier stamp-only locks — this lock
// pins the 4→5 diff to exactly the stamp plus the gen5ContentLines above,
// and requires that the superseded gen-4 gates line reads as machine-owned
// (Pending), never as a local edit (SkippedUnrecognized).
func TestGen4To5IsStampPlusDeclaredContent(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		raw, err := os.ReadFile(filepath.Join("testdata", "ccq-gen4", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	seen := map[string]bool{}
	for _, r := range reports {
		switch r.Path {
		case "WORKFLOW.md", "CLAUDE.md":
			seen[r.Path] = true
			if len(r.Unrecognized) > 0 {
				t.Errorf("%s: superseded machine lines misread as local edits: %v", r.Path, r.Unrecognized)
			}
			if r.State != Pending {
				t.Errorf("%s: want Pending, got %v", r.Path, r.State)
				continue
			}
			for _, line := range strings.Split(r.Diff, "\n") {
				if !strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "-") {
					continue
				}
				if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
					continue
				}
				if strings.Contains(line, "template_version") || strings.Contains(line, "spine:begin") {
					continue
				}
				if isGen5ContentDiffLine(line) {
					continue
				}
				if isGen6ContentDiffLine(line) { // gen 6's conscious content edit; see gen5to6_test.go
					continue
				}
				t.Errorf("%s: unexpected changed line %q — 4→5 must be stamp plus declared gen-5 content only", r.Path, line)
			}
		}
	}
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		if !seen[name] {
			t.Errorf("%s: never reported by Run — the lock did not exercise it", name)
		}
	}
}
