package update

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// gen8ContentLines are the emitted-content changes gen 8 ships (I020): the
// new "Stage cursor (consistency rule)" section, inserted between the
// doctrine paragraph and "## Model routing". Gen 8 is a pure addition (no
// gen-7 line is reworded or dropped), so every changed line is a "+" row —
// there is no gen-8 "-" side to declare.
//
// M9 (I027) maintainer note: this one-sided shape is deliberate, not an
// oversight — contrast gen9ContentLines in gen8to9_test.go, which lists
// both a "-" (dropped gen-8 line) and a "+" (its gen-9 replacement) because
// gen 9 reworded a line instead of purely adding one. Each generation's set
// has exactly as many sides as that generation's diff actually has.
var gen8ContentLines = map[string]bool{
	"## Stage cursor (consistency rule)": true,
	"Stages run **in order**; none may be silently skipped (the miss mode is a handoff that names an":                                         true,
	"abbreviated path — e.g. \"grill -> to-spec -> build\" quietly dropping `issues`/`to-tickets`). To":                                       true,
	"prevent it, every SDD effort's `.superpowers/sdd/progress.md` opens with a machine-readable":                                             true,
	"stage cursor block — one `<!-- spine:cursor -->` block naming the effort, PRD, ticket range, and":                                        true,
	"every stage's marker. `[x]` marks a done stage, `[<]` marks YOU ARE HERE (exactly one, among the non-done stages), `[ ]` marks pending.": true,
	"The cursor is the single source of truth for \"where are we\"; check it at session start before acting.":                                 true,
	"Grammar reference (documentation only — the real block lives at the head of":                                                             true,
	"`.superpowers/sdd/progress.md`, never here):":                                                                                            true,
	"<!-- spine:cursor -->":          true,
	"effort: <kebab-name>":           true,
	"prd: docs/specs/<file>.md":      true,
	"tickets: I0NN-I0MM | prefix I0": true,
	"stages: grill[x] prd[x] issues[x] implement[<] functional-test[ ] review[ ] verify[ ] ship[ ] ...": true,
	"<!-- /spine:cursor -->": true,
	"**Handoff rule:** `/handoff` and any resume/kickoff prompt MUST embed the verbatim output of `spine cursor` — a prose paraphrase of stage state is incomplete; the reader can't see which upstream stage was skipped from a summary alone.": true,
}

// isGen8ContentDiffLine reports whether a unified-diff line carries one of
// the gen-8 content additions above, or is a bare added/removed blank line
// from the new section's spacing.
func isGen8ContentDiffLine(line string) bool {
	if len(line) == 0 || (line[0] != '+' && line[0] != '-') {
		return false
	}
	body := strings.TrimSpace(line[1:])
	return body == "" || gen8ContentLines[body]
}

// The ccq-gen7 fixture is the gen-7 output of the ccq-gen5 fixture's
// lineage (generated BY GEN-7 CODE — a straight render of the pre-I020
// template with Version: 7 — before the gen-8 Stage cursor section
// landed). A pristine gen-7 file must update cleanly: zero unrecognized
// lines, and the diff is exactly the stamp bump plus the declared gen-8
// content — proving I020's ticket AC "a pristine gen-7 WORKFLOW.md updates
// cleanly".
func TestGen7To8PristineUpdatesCleanly(t *testing.T) {
	dir := t.TempDir()
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		raw, err := os.ReadFile(filepath.Join("testdata", "ccq-gen7", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	seen := map[string]bool{}
	for _, r := range reports {
		switch r.Path {
		case "WORKFLOW.md", "CLAUDE.md":
			seen[r.Path] = true
			if len(r.Unrecognized) > 0 {
				t.Errorf("%s: pristine gen-7 lines misread as local edits: %v", r.Path, r.Unrecognized)
			}
			if r.State != Pending {
				t.Errorf("%s: want Pending, got %v", r.Path, r.State)
				continue
			}
			for _, line := range strings.Split(r.Diff, "\n") {
				if !strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "-") {
					continue
				}
				if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
					continue
				}
				if strings.Contains(line, "template_version") || strings.Contains(line, "spine:begin") {
					continue
				}
				if isGen8ContentDiffLine(line) {
					continue
				}
				if isGen9ContentDiffLine(line) { // gen 9's conscious content edit; see gen8to9_test.go
					continue
				}
				t.Errorf("%s: unexpected changed line %q — 7→8 must be stamp plus declared gen-8 content only", r.Path, line)
			}
		}
	}
	for _, name := range []string{"WORKFLOW.md", "CLAUDE.md"} {
		if !seen[name] {
			t.Errorf("%s: never reported by Run — the lock did not exercise it", name)
		}
	}
}

// End-to-end against a VERBATIM copy of ultima-dci-edition's real WORKFLOW.md
// (hbmview_test.go style: a real repo's real stranded/hand-authored file,
// not a synthetic fixture). ultima's "## Stage cursor (consistency rule)"
// section predates the I018 cursor grammar and was hand-written before spine
// owned this section at all. It must be recognized as superseded content —
// not a local edit — so a plain `spine update` reports zero unrecognized
// lines and replaces the section wholesale with the gen-8 spine-owned one.
func TestUltimaHandWrittenCursorSectionSuperseded(t *testing.T) {
	dir := t.TempDir()
	raw, err := os.ReadFile(filepath.Join("testdata", "ultima", "WORKFLOW.md"))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "WORKFLOW.md"), raw, 0o644); err != nil {
		t.Fatal(err)
	}

	reports, err := Run(Options{Dir: dir})
	if err != nil {
		t.Fatal(err)
	}
	wf := report(t, reports, "WORKFLOW.md")
	if len(wf.Unrecognized) > 0 {
		t.Fatalf("ultima's hand-written Stage cursor section misread as local edits: %v", wf.Unrecognized)
	}
	if wf.State != Pending {
		t.Fatalf("want Pending (plain update must claim the file), got state=%v diff:\n%s", wf.State, wf.Diff)
	}

	if _, err := Run(Options{Dir: dir, Write: true}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(dir, "WORKFLOW.md"))
	if err != nil {
		t.Fatal(err)
	}
	gotStr := string(got)

	if n := strings.Count(gotStr, "## Stage cursor (consistency rule)"); n != 1 {
		t.Errorf("want exactly one Stage cursor section (replaced, not duplicated), got %d", n)
	}
	for _, want := range []string{
		"exactly one, among the non-done stages", // canonical marker-semantics wording (I018 post-fix)
		"spine cursor",                           // handoff rule: verbatim `spine cursor` output
		"<!-- spine:cursor -->",                  // grammar reference embedded as documentation
		"template_version: 9",
	} {
		if !strings.Contains(gotStr, want) {
			t.Errorf("migrated WORKFLOW.md missing %q", want)
		}
	}
	for _, stale := range []string{
		"WORKFLOW stage checklist", // ultima's old (pre-I018) hand-written wording
		"← YOU ARE HERE",
		"MUST carry the stage cursor **verbatim**", // superseded handoff-rule wording
	} {
		if strings.Contains(gotStr, stale) {
			t.Errorf("stale hand-written wording survived migration: %q", stale)
		}
	}
}
